[versions]
nizi-patcher = "20.0.0"
smali = "3.0.4"
guava = "32.1.4-jre"
gson = "2.10.2"

[libraries]
nizi-patcher = { module = "app.pamilg8:nizi-patcher", version.ref = "nizi-patcher" }
smali = { module = "com.android.tools.smali:smali", version.ref = "smali" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
